### ISSUE TITLE
Cool library - I happened to write a similar one around the same time

### ISSUE THREAD

**Issue by eejdoowad** [asimen1/chrome-ext-messenger#1]
Check it out. https://github.com/eejdoowad/mosi.

Some notable differences:
* Mosi uses promises
* The targets are more flexible and powerful
* Mosi has a function that sends a request to target nodes and returns a promise for the response from every node
* The API is super simple, just 3 functions: init, msg, get

**Comment by asimen1** [comment]
Thanks eejdoowad, closing since it's not really an issue.

I saw your library before but I wanted to create something that is more approachable to chrome developers by making it as close as possible to chrome's original message passing API but without handling all it's quirks (especially for sending messages which require relaying in the background page).
So to ease the chrome developer's life, my library uses callbacks and similar syntax and arguments of the original API.

I added only a few useful improvements like sending messages to multiple listeners/ports at once, listeners identied by string names, automatic async support, connected/disconnect port handler, etc...

Cheers :smile:
